# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: eeee35a89e69d5772bdee97db1a6a898467b686e # frozen: v1.0
    hooks:
      - id: fmt
      - id: clippy
        args: [--all, --all-features]
      - id: cargo-check
  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/crate-ci/typos
    rev: cf5f1c29a8ac336af8568821ec41919923b05a83 # frozen: v1.45.1
    hooks:
      - id: typos
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e # frozen: v0.48.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/Baseline|^README.md
      - id: end-of-file-fixer
        exclude: ^tests/Baseline|^doc/autogen|^doc/_static
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [pre-commit]
        exclude: ^README.md

exclude: .github/workflows/release.yml|tests/cmd/do_not_touch_unmodified.in/.*
