name: Check

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  cargo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: moonrepo/setup-rust@v1
      - name: Install tree-sitter-cli
        run: |
          npm install -g tree-sitter-cli
      - name: Test
        run: cargo test

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy,rustfmt
      - uses: j178/prek-action@v2.0.5

  uv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      - name: Build with uv
        run: |
          uv build
