name: Check

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  cargo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: moonrepo/setup-rust@v1
      - name: Install tree-sitter-cli
        run: |
          npm install -g tree-sitter-cli
      - name: Test
        run: cargo test

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy,rustfmt
      - uses: j178/prek-action@v2.0.6

  uv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      - name: Build with uv
        run: |
          uv build
